[package]
name = "json-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json-gen = "0.2.3"
serde_json = "1.0"
